version: 0.2

env:
  variables:
    TF_VERSION: "1.5.0"
    AWS_REGION: "eu-north-1"
    TF_STATE_BUCKET: "lnybro-terraform-state-bucket" # specify your S3 bucket for Terraform state
    TF_STATE_KEY: "terraform/split-test-analyzer.tfstate" # specify the state key

phases:
  install:
    runtime-versions:
      nodejs: 22.x
    commands:
      - echo "Installing node dependencies..."
      - cd packages/api/POST/data && yarn install
  pre_build:
    commands:
      - echo "Running tests..."
      - cd packages/api/POST/data && yarn test
  build:
    commands:
      - cd packages/api/POST/data && yarn workspaces focus --production
      - echo "Building the Node.js application..."
      - cd packages/api/POST/data && yarn build
      - cd packages/api/POST/data && yarn zip

  post_build:
    commands:
      - echo "Installing Terraform..."
      - curl -Lo terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version
      - echo "Terraform installed"
      
      - echo "Setting up AWS credentials..."
      - aws sts get-caller-identity
      - echo "Initializing Terraform..."
      - cd infrastructure
      - terraform init -backend-config="bucket=${TF_STATE_BUCKET}" -backend-config="key=${TF_STATE_KEY}" -backend-config="region=${AWS_REGION}"
      
      - echo "Running Terraform Plan..."
      - terraform plan -out=tfplan
      - echo "Applying Terraform plan..."
      - terraform apply -auto-approve tfplan

      - echo "Deployment complete!"
      - terraform output

artifacts:
  files:
    - '**/*'  # Include any output files if needed